## Initial EDA

In [63]:
import pandas as pd

# import data from csv-file
df = pd.read_csv("../data/events_full.csv")

df

,event_id,name,url,image_url,date,time,status,venue_id,fetched_at,category_id,...,genre,subgenre,venue_name,venue_city,venue_address,venue_lat,venue_lon,price_min,price_max,price_currency
0,Z698xZq2Z1kAoaYe7,STOCKHOLM INTERNATIONAL TAP DANCE FESTIVAL,https://www.ticketmaster.se/event/stockholm-in...,https://s1.ticketm.net/dam/a/d2f/8582cce8-a129...,2026-04-05,20:00:00,onsale,Z598xZq2Z1dk7,2026-04-01T20:51:19.399548+00:00,1,...,Dance,Dance,NaN,Stockholm,Mariatorget 3,59.318160,18.063640,NaN,NaN,NaN
1,Z698xZq2Z16vv_fM-U,Hussam Al Rassam,https://www.ticketmaster.se/event/hussam-al-ra...,https://s1.ticketm.net/dam/a/852/8e7f56cd-e0e6...,2026-04-08,19:30:00,onsale,Z198xZq2ZAv1,2026-04-01T20:51:19.399548+00:00,2,...,Other,Other,Cirkus,Stockholm,Djurgårdsslätten 43-45,59.324570,18.099690,NaN,NaN,NaN
2,Z698xZq2Z1kqkOVqb,MAMMA MIA! THE PARTY,https://www.ticketmaster.se/event/mamma-mia-th...,https://s1.ticketm.net/dam/e/749/9b2f6860-5355...,2026-04-10,18:30:00,onsale,Z698xZq2ZadxS,2026-04-01T20:51:19.399548+00:00,3,...,Theatre,Musical,Tyrol,Stockholm,Lilla Allmänna Gränd 2,59.324127,18.096259,NaN,NaN,NaN
3,Z698xZq2Z1kaJxA4_,Daniel Midas w Sztokholmie,https://www.ticketmaster.se/event/daniel-midas...,https://s1.ticketm.net/dam/a/860/7bdfbbf9-502d...,2026-04-10,20:00:00,onsale,Z698xZq2ZaA1u,2026-04-01T20:51:19.399548+00:00,4,...,Comedy,Comedy,Bio Skandia,Stockholm,Drottninggatan 82,59.335440,18.059980,NaN,NaN,NaN
4,Z698xZq2Z16vPaqZG6,MAMMA MIA! THE PARTY,https://www.ticketmaster.se/event/mamma-mia-th...,https://s1.ticketm.net/dam/e/581/fd4107d3-b072...,2026-04-11,13:00:00,onsale,Z698xZq2ZadxS,2026-04-01T20:51:19.400327+00:00,5,...,Theatre,Miscellaneous,Tyrol,Stockholm,Lilla Allmänna Gränd 2,59.324127,18.096259,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,Z698xZq2Z16eZbfvax,MAMMA MIA! THE PARTY,https://www.ticketmaster.se/event/mamma-mia-th...,https://s1.ticketm.net/dam/a/08d/3e62af05-2974...,2026-11-28,13:00:00,onsale,Z698xZq2ZadxS,2026-04-01T20:51:19.403352+00:00,3,...,Theatre,Musical,Tyrol,Stockholm,Lilla Allmänna Gränd 2,59.324127,18.096259,NaN,NaN,NaN
156,Z698xZq2Z16vubuZj9,MAMMA MIA! THE PARTY,https://www.ticketmaster.se/event/mamma-mia-th...,https://s1.ticketm.net/dam/a/08d/3e62af05-2974...,2026-11-28,19:30:00,onsale,Z698xZq2ZadxS,2026-04-01T20:51:19.403352+00:00,3,...,Theatre,Musical,Tyrol,Stockholm,Lilla Allmänna Gränd 2,59.324127,18.096259,NaN,NaN,NaN
157,Z698xZq2Z1kfOpe8v,ARLO PARKS - DESIRE TOUR,https://www.ticketmaster.se/event/arlo-parks-d...,https://s1.ticketm.net/dam/a/492/744f8651-20a1...,2026-12-02,20:00:00,onsale,Z698xZq2Za7j6,2026-04-01T20:51:19.403352+00:00,17,...,Alternative,Alternative Rock,NaN,Stockholm,Styckmästergatan 10,59.292240,18.080120,NaN,NaN,NaN
158,Z698xZq2Z1ANjx7Z,"RUSH, FIFTY SOMETHING, Platinum Tickets",https://www.ticketmaster.se/event/rush-fifty-s...,https://s1.ticketm.net/dam/a/6bd/c02199ad-8d22...,2027-04-08,20:00:00,onsale,Z698xZq2Za7YE,2026-04-01T20:51:19.403352+00:00,6,...,Rock,Pop,NaN,Stockholm,Globentorget 2,59.294160,18.080810,NaN,NaN,NaN
159,Z698xZq2Z17_OjN,Sofia GA 0522 Real - Do not purchases,https://www.ticketmaster.se/event/sofia-ga-052...,https://s1.ticketm.net/dam/c/368/b70b1d5a-ce61...,2027-12-22,01:00:00,onsale,Z698xZq2ZaejP,2026-04-01T20:51:19.403352+00:00,9,...,Family,Other,Ticketmaster,Stockholm,Centralplan 15,59.333530,18.057200,NaN,NaN,NaN

In [64]:
df.head()

,event_id,name,url,image_url,date,time,status,venue_id,fetched_at,category_id,...,genre,subgenre,venue_name,venue_city,venue_address,venue_lat,venue_lon,price_min,price_max,price_currency
0,Z698xZq2Z1kAoaYe7,STOCKHOLM INTERNATIONAL TAP DANCE FESTIVAL,https://www.ticketmaster.se/event/stockholm-in...,https://s1.ticketm.net/dam/a/d2f/8582cce8-a129...,2026-04-05,20:00:00,onsale,Z598xZq2Z1dk7,2026-04-01T20:51:19.399548+00:00,1,...,Dance,Dance,NaN,Stockholm,Mariatorget 3,59.318160,18.063640,NaN,NaN,NaN
1,Z698xZq2Z16vv_fM-U,Hussam Al Rassam,https://www.ticketmaster.se/event/hussam-al-ra...,https://s1.ticketm.net/dam/a/852/8e7f56cd-e0e6...,2026-04-08,19:30:00,onsale,Z198xZq2ZAv1,2026-04-01T20:51:19.399548+00:00,2,...,Other,Other,Cirkus,Stockholm,Djurgårdsslätten 43-45,59.324570,18.099690,NaN,NaN,NaN
2,Z698xZq2Z1kqkOVqb,MAMMA MIA! THE PARTY,https://www.ticketmaster.se/event/mamma-mia-th...,https://s1.ticketm.net/dam/e/749/9b2f6860-5355...,2026-04-10,18:30:00,onsale,Z698xZq2ZadxS,2026-04-01T20:51:19.399548+00:00,3,...,Theatre,Musical,Tyrol,Stockholm,Lilla Allmänna Gränd 2,59.324127,18.096259,NaN,NaN,NaN
3,Z698xZq2Z1kaJxA4_,Daniel Midas w Sztokholmie,https://www.ticketmaster.se/event/daniel-midas...,https://s1.ticketm.net/dam/a/860/7bdfbbf9-502d...,2026-04-10,20:00:00,onsale,Z698xZq2ZaA1u,2026-04-01T20:51:19.399548+00:00,4,...,Comedy,Comedy,Bio Skandia,Stockholm,Drottninggatan 82,59.335440,18.059980,NaN,NaN,NaN
4,Z698xZq2Z16vPaqZG6,MAMMA MIA! THE PARTY,https://www.ticketmaster.se/event/mamma-mia-th...,https://s1.ticketm.net/dam/e/581/fd4107d3-b072...,2026-04-11,13:00:00,onsale,Z698xZq2ZadxS,2026-04-01T20:51:19.400327+00:00,5,...,Theatre,Miscellaneous,Tyrol,Stockholm,Lilla Allmänna Gränd 2,59.324127,18.096259,NaN,NaN,NaN

In [65]:
# check RangeIndex & non-null
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160 entries, 0 to 159
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   event_id        160 non-null    object
 1   name            160 non-null    object
 2   url             160 non-null    object
 3   image_url       160 non-null    object
 4   date            160 non-null    object
 5   time            156 non-null    object
 6   status          160 non-null    object
 7   venue_id        160 non-null    object
 8   fetched_at      160 non-null    object
 9   category_id     160 non-null    int64
 10  segment         160 non-null    object
 11  genre           160 non-null    object
 12  subgenre        160 non-null    object
 13  venue_name      134 non-null    object
 14  venue_city      160 non-null    object
 15  venue_address   159 non-null    object
 16  venue_lat       160 non-null    float64
 17  venue_lon       160 non-null    float64
 18  price_min       0 non-null      float64
 19  price_max       0 non-null      float64
 20  price_currency  0 non-null      float64
dtypes: float64(5), int64(1), object(15)
memory usage: 26.4+ KB

In [66]:
df.columns

Index(['event_id', 'name', 'url', 'image_url', 'date', 'time', 'status',
       'venue_id', 'fetched_at', 'category_id', 'segment', 'genre', 'subgenre',
       'venue_name', 'venue_city', 'venue_address', 'venue_lat', 'venue_lon',
       'price_min', 'price_max', 'price_currency'],
      dtype='object')

In [67]:
# descriptive statistics of summative statistics (only numerical columns)
df.describe().T

,count,mean,std,min,25%,50%,75%,max
category_id,160.0,5.412500,3.335322,1.00000,3.000000,5.000000,6.000000,17.00000
venue_lat,160.0,59.324916,0.018678,59.29045,59.324127,59.324127,59.324127,59.37254
venue_lon,160.0,18.081427,0.029703,18.00041,18.080810,18.096259,18.096259,18.11903
price_min,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_max,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price_currency,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
# check number of rows and columns
print(f"Rows: {df.shape[0]}, Cols: {df.shape[1]}")

Rows: 160, Cols: 21

## Exploratory EDA

In [69]:
import duckdb

df["segment"].value_counts()

segment
Arts & Theatre    100
Music              55
Miscellaneous       4
Sports              1
Name: count, dtype: int64

In [70]:
df["genre"].value_counts()

genre
Theatre             93
Rock                20
Other               12
Hip-Hop/Rap          8
Dance/Electronic     7
Dance                4
Comedy               3
Family               3
Latin                3
Folk                 2
Alternative          2
Martial Arts         1
Food & Drink         1
Metal                1
Name: count, dtype: int64

In [73]:
ax = df["genre"].value_counts().plot(
    kind="bar",
    ylabel="Number of genres",
    title="Genre",
)

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [ ]:
# how many different events do we have?
duckdb.sql("""--sql
SELECT
DISTINCT(name)
FROM df
""")

In [ ]:
# how many, and which events is there a specific date
# using Window functions OVER() to aggregate over the full result set
result = duckdb.sql("""
    SELECT
        name,
        date,
        COUNT(*) OVER() AS total_events
    FROM df
    WHERE date = '2026-04-10'
""").df()

print(result.to_string(index=False))

In [ ]:
# which days has most events?
duckdb.sql("""
SELECT
    date,
    count(*) AS num_events
    FROM df
    GROUP BY date
    ORDER BY num_events DESC
    LIMIT 5
""")